# This is a workflow to 

name: Sync Code to Taktile Code Node

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync-code:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Read Python file
        id: read_code_files
        run: |
          FILE_PATH="taktile-take-home-challenge/Multiply.py"
          CONTENT=$(cat $FILE_PATH | jq -Rs .)
          echo "code=$CONTENT" >> $GITHUB_OUTPUT

      # Runs a set of commands using the runners shell
      - name: List Decision Flows
        env:
          API_KEY: ${{ secrets.TAKTILE_API_KEY }}
        run: |
          curl -X 'POST' \
            'https://eu-central-1.taktile-org.decide.taktile.com/run/api/v1/flows/list-decision-graphs/sandbox/decide' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'X-Api-Key: <API_KEY>' \
            -d '{
            "data": {
              "organization_name": "NB36"
            },
            "metadata": {
            "version": "v1.0",
            "entity_id": "string"
            },
            "control": {
              "execution_mode": "sync"
            }
          }'
